# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
puts 'clearing database'
Article.delete_all
Event.destroy_all
User.destroy_all

puts 'creating user'
User.create(email: 'user1@hotmail.com', password: '123456')
puts 'creating articles'
user = User.last
Article.create(user: user, category: 'Primario',title: 'Los Alumnos empezaron el ciclo lectivo 2020', photo: 'https://res.cloudinary.com/dw7ox75dg/image/upload/v1585156076/44267120_1919928638053275_7998990119052771328_o.jpg', subtitle: 'Los Alumnos empezaron el ciclo lectivo 2020 , y los padres estuvieron presentes',
 content1: 'ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit,
 fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.
 ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.
 ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.
 ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.' )
Article.create(user: user, category: 'Secundario',title: 'Los alumnos enseñaron educacion vial a alumnos de primario', photo: 'https://res.cloudinary.com/dw7ox75dg/image/upload/v1585156072/40029739_1854585191254287_6456261823657148416_o.jpg', subtitle: 'Los alumnos enseñaron educacion vial a alumnos de primario',
 content1: 'ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit,
 fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.
 ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.
 ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.
 ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.' )
Article.create(user: user, category: 'I.B',title: 'May 2020 examinations will no longer be held', photo: 'https://content.thriveglobal.com/wp-content/uploads/2019/10/7-Reasons-To-Become-A-Teacher-.jpg', subtitle: 'Our students, their well-being and their progression in future stages of life have been at the forefront of our thinking as we respond to this extraordinary pandemic',
 content1: 'ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit,
 fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.
 ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.
 ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.
 ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.' )
Article.create(user: user, category: 'Secundario',title: 'Inaguramos el nuevo comedor', photo: 'https://res.cloudinary.com/dw7ox75dg/image/upload/v1585156086/73188402_2556116157767850_6243152740499849216_n.jpg', subtitle: 'La inaguracion del nuevo comedor del Secundario',
  content1: 'ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit,
 fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.
 ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.
 ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.
 ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.' )
Article.create(user: user, category: 'Primario',title: 'Los Alumnos empezaron el ciclo lectivo 2020', photo: 'https://res.cloudinary.com/dw7ox75dg/image/upload/v1585156076/44267120_1919928638053275_7998990119052771328_o.jpg', subtitle: 'Los Alumnos empezaron el ciclo lectivo 2020 , y los padres estuvieron presentes',
 content1: 'ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit,
 fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.
 ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.
 ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.
 ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.' )
Article.create(user: user, category: 'Secundario',title: 'Los alumnos enseñaron educacion vial a alumnos de primario', photo: 'https://res.cloudinary.com/dw7ox75dg/image/upload/v1585156072/40029739_1854585191254287_6456261823657148416_o.jpg', subtitle: 'Los alumnos enseñaron educacion vial a alumnos de primario',
 content1: 'ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit,
 fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.
 ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.
 ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.
 ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.' )
Article.create(user: user, category: 'I.B',title: 'May 2020 examinations will no longer be held', photo: 'https://content.thriveglobal.com/wp-content/uploads/2019/10/7-Reasons-To-Become-A-Teacher-.jpg', subtitle: 'Our students, their well-being and their progression in future stages of life have been at the forefront of our thinking as we respond to this extraordinary pandemic',
 content1: 'ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit,
 fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.
 ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.
 ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.
 ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.' )
Article.create(user: user, category: 'Secundario',title: 'Inaguramos el nuevo comedor', photo: 'https://res.cloudinary.com/dw7ox75dg/image/upload/v1585156086/73188402_2556116157767850_6243152740499849216_n.jpg', subtitle: 'La inaguracion del nuevo comedor del Secundario',
  content1: 'ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit,
 fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.
 ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.
 ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.
 ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.' )
Article.create(user: user, category: 'Institucional',title: 'No habra clases el dia 22 de abril', photo: 'https://res.cloudinary.com/dw7ox75dg/image/upload/v1585156046/61489059_2240313456014790_473916157548560384_n.jpg', subtitle: 'Los Alumnos empezaron el ciclo lectivo 2020 , y los padres estuvieron presentes',
 content1: 'ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit,
 fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.
 ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.
 ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.
 ipsum dolor sit amet, consectetur adipisicing elit. Maiores sit, fuga facere autem suscipit. Nihil recusandae odio inventore repudiandae eveniet molestias corrupti delectus, consequatur suscipit eum, vitae porro enim, numquam.' )
puts 'creating events'
Event.create(user: user, title: 'Dia de la bandera', description: 'Se celebra el 20 de junio el dia de nuestra bandera los esperamos a todos', date: '20/06/2020', time: '08', photo: 'https://www.infobae.com/new-resizer/q1LE7pSgJWJdnLNViM1TvjYc_oU=/750x0/filters:quality(100)/s3.amazonaws.com/arc-wordpress-client-uploads/infobae-wp/wp-content/uploads/2017/10/20112718/bandera-argentina-ok.jpg')
Event.create(user: user, title: 'Dia de la independencia', description: 'Se celebra el 9 de julio el dia de nuestra independencia los esperamos a todos', date: '09/07/2020', time: '08', photo: 'https://www.noticiasdel6.com/wp-content/uploads/2018/06/3-1.gif')
Event.create(user: user, title: 'Dia de la bandera', description: 'Se celebra el 20 de junio el dia de nuestra bandera los esperamos a todos', date: '20/06/2020', time: '08', photo: 'https://www.infobae.com/new-resizer/q1LE7pSgJWJdnLNViM1TvjYc_oU=/750x0/filters:quality(100)/s3.amazonaws.com/arc-wordpress-client-uploads/infobae-wp/wp-content/uploads/2017/10/20112718/bandera-argentina-ok.jpg')
Event.create(user: user, title: 'Celebracion del 25 de mayo ', description: 'Se celebra el 20 de junio el dia de nuestra bandera los esperamos a todos', date: '25/05/2020', time: '08', photo: 'https://res.cloudinary.com/dw7ox75dg/image/upload/v1585156055/60997228_2240313369348132_358752390532300800_n.jpg')
puts 'finsh events'
